{% set name = "cwl-upgrader" %}
{% set version = "1.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0d4e514d32d96b60c5300de9baa30a583b09066c9aa78dd6aa7744164d72dc5c

build:
  noarch: python
  entry_points:
    - cwl-upgrader = cwlupgrader.main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - ruamel.yaml >=0.16.0,<0.19
    - schema-salad
    - setuptools

test:
  imports:
    - cwlupgrader
  commands:
    - pip check
    - cwl-upgrader --help
    - python -m pytest -n auto --pyargs cwlupgrader
  requires:
    - pip
    - pytest-xdist
    - python {{ python_min }}

about:
  home: https://github.com/common-workflow-language/cwl-upgrader
  license: Apache-2.0
  license_file:
    - LICENSE.txt
  summary: This is a standalone upgrader for Common Workflow Language documents from version draft-3, v1.0, and v1.1 to v1.2
  dev_url: https://github.com/common-workflow-language/cwl-upgrader

extra:
  recipe-maintainers:
    - mr-c
    - kinow
