{% set name = "cwl-upgrader" %}
{% set version = "1.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cwl-upgrader-{{ version }}.tar.gz
  sha256: d0ca216df461653b324aa42f5b16fb2403ec88729ad42c3ee2e3264b4811029f

build:
  noarch: python
  entry_points:
    - cwl-upgrader = cwlupgrader.main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ruamel.yaml >=0.16.0,<0.17.22
    - schema-salad
    - setuptools

test:
  imports:
    - cwlupgrader
  commands:
    - pip check
    - cwl-upgrader --help
    - python -m pytest -n auto --pyargs cwlupgrader
  requires:
    - pip
    - pytest-xdist

about:
  home: https://github.com/common-workflow-language/cwl-upgrader
  license: Apache-2.0
  license_file:
    - LICENSE.txt
  summary: This is a standalone upgrader for Common Workflow Language documents from version draft-3, v1.0, and v1.1 to v1.2
  dev_url: https://github.com/common-workflow-language/cwl-upgrader

extra:
  recipe-maintainers:
    - mr-c
    - kinow
